project_id = "wzpjmnjzfismjozhapmq"

[functions.generate-firm-description]
verify_jwt = false

[functions.generate-meta-description]
verify_jwt = false

[functions.restore-backup]
verify_jwt = true

[functions.upload-firms-excel]
verify_jwt = true

[functions.sitemap]
verify_jwt = false

[functions.serper-search]
verify_jwt = true

[functions.add-serper-firms]
verify_jwt = true

[functions.serper-account]
verify_jwt = true

[functions.fix-category-names]
verify_jwt = true

